### PR TITLE
Update to embedded-hal v1.0

### PR DESCRIPTION
**Pull request by Dirbaio**
- Update to embedded-hal v1.0
- wip patch, remove when v1.0 is actually released.

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks!

Once the release is out and settled, I think we can also phase out the e-h 0.2 support in all future releases. However, it's probably good to leave it in the codebase initially.

**Comment by rursprung** [comment]
@dbrgn e-h 1.0.0 is out now 😄

**Review by newAM — APPROVED** [review]

**Comment by dbrgn** [comment]
🥳

**Comment by dbrgn** [comment]
I'll publish the non-RC version today.

**Pull request merged**
