### PR TITLE
Add transactions to SpiDevice read/write methods

### PR DESCRIPTION
**Pull request by teotwaki**
This addresses #71.

### CODE REVIEW

**Comment by teotwaki** [comment]
@dbrgn Not sure if you get notifications without being mentioned, so pinging you for visibility.

Could you approve the CI run on this PR?

Thanks, and have a nice weekend!

**Comment by dbrgn** [comment]
CI run approved!

I hope I can take a look at this soon-ish. If I forget, feel free to ping me 🙂

**Comment by dbrgn** [comment]
@teotwaki with #75, the `1-alpha` branch was merged into `main`. Do you think you could re-apply your changes to `main` and update your pull request? Ideally with 1, 2 tests as well.

**Comment by teotwaki** [comment]
Sure; I'm just back from holiday so I'll look at this in the coming days to see if it's still relevant with the new embedded-hal revisions.

**Pull request closed without merging**
