### PR TITLE
spi: Adds mock implementation for WriteIter

### PR DESCRIPTION
**Pull request by silvergasp**
Happy for a few runs at this as I'm relatively new to rust.

### CODE REVIEW

**Review by dbrgn — CHANGES_REQUESTED** [review]
Thanks! I wonder if you could delegate to the regular `Write` implementation, similar to the way it was done with I2C here: https://github.com/dbrgn/embedded-hal-mock/pull/44

**Comment by dbrgn** [comment]
@silvergasp are you interested in doing the suggested change, or should someone else take over your branch?

**Comment by silvergasp** [comment]
Oh yeah sorry I missed this one, I'll take another pass at it

**Comment by dbrgn** [comment]
@silvergasp friendly reminder 🙂 If you don't have time, just let me know.

**Comment by dbrgn** [comment]
Hmm, I just pushed a version that calls self.write, but I realized that while it re-uses code, it makes error reporting worse (since error messages on missing expectation will mention `spi::write`, and not `spi::write_iter`). I'll undo that commit.

**Review by dbrgn — APPROVED** [review]
Thanks, I think this can now be merged!

**Pull request merged**
