### PR TITLE
Release v0.10.0

### PR DESCRIPTION
**Pull request by dbrgn**
I merged the RC changelogs and added migration steps.

### CODE REVIEW

**Review by newAM — APPROVED** [review]
LGTM!

**Comment by ryankurte** [comment]
lgtm! though it might be nice to land #89 first?

**Comment by dbrgn** [comment]
@ryankurte I reviewed #89 and there are still a few issues. I'd prefer to publish this release (so people can use e-h 1.0), but we can quickly publish additional new versions once the MRs are ready to land!

**Comment by dbrgn** [comment]
Version 0.10.0 is published on crates.io!

**Pull request merged**
