### PR TITLE
Adapt to embedded-hal-1.0.0-alpha.1

### PR DESCRIPTION
**Pull request by eldruin**
Here the adaptions necessary for embedded-hal `1.0.0-alpha.1`.

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! I think requiring Rust >=1.34 would be fine, what do you think?

**Comment by eldruin** [comment]
Good point. The MSRV in `embedded-hal` had to be raised to Rust 1.35 due to an issue with associated constants in the ADC trait. So far that will be the MSRV of `embedded-hal` 1.0.0 so actually I would say the MSRV of this crate should be raised to 1.35 as well.
I will revert the commit adding void, update the MSRV and bump the minor version of this crate in this branch.

**Comment by dbrgn** [comment]
Makes sense!

**Comment by eldruin** [comment]
Done :)

**Comment by ryankurte** [comment]
Looks good! Blocked on https://github.com/rust-embedded/embedded-hal/issues/177 (which I've mentioning everywhere useful so we have a list of pending PRs when we ship `v1.0.0`)

**Comment by dbrgn** [comment]
@niclashoyer updated your branch to the latest alpha, so let's continue this discussion in #39.

**Pull request closed without merging**
